name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        sudo apt update -y
        sudo apt install -y libfontconfig-dev
    - name: Build 
      run: cargo build
    - name: Test
      run: cargo test
